# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 13:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userdemandcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandcategory', models.CharField(max_length=120)),
                ('demandtext', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usertype', models.CharField(choices=[('VOTER', 'Voter'), ('CANDIDATE', 'Candidate')], default='Voter', max_length=2)),
                ('State', models.CharField(max_length=120)),
                ('District', models.CharField(max_length=120)),
                ('Pincode', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('AadharNo', models.PositiveIntegerField(error_messages={'unique': 'A user with that AadharNo. already exists.'}, unique=True, validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
